### ISSUE TITLE
 Invalid argument supplied for foreach in WizardController::keepOnlyListTypeAndCTypeInDefaultValues

### ISSUE THREAD

**Issue by sypets** [christophlehmann/pagetreefilter#18]
```
1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Invalid argument supplied for foreach() in /var/www/site-uol11/htdocs/typo3conf/ext/pagetreefilter/Classes/Controller/WizardController.php line 162

```

`WizardController:: keepOnlyListTypeAndCTypeInDefaultValues`

When debugging this, I have an array $wizards with one entry which only contains a 'header' entry. I am not sure if this is (configuration) problem on my end. The problem did not occur when testing this extension with TYPO3 v10. I am now testing with v11.

```
$wizards = [
    'common' => [
       'header' => 'Typical page element'
    ],
   // ....
]
```

## Versions

pagetreefilter: 1.5.0 or main
TYPO3 core 11.5.16

**Comment by christophlehmann** [comment]
I can imagine, that the group header remains, when you have no access to the custom elements or you moved them to another group.
