### ISSUE TITLE
TypeError because of return value of isWizardEnabled()

### ISSUE THREAD

**Issue by sypets** [christophlehmann/pagetreefilter#2]
Return value of Lemming\PageTreeFilter\Utility\ConfigurationUtility::isWizardEnabled() must be of the type bool, string returned

```
in /var/www/site-uol/htdocs/typo3conf/ext/pagetreefilter/Classes/Utility/ConfigurationUtility.php line 24
        }

        $isEnabledForNormalUser = $backendUser->getTSConfig()['tx_pagetreefilter.']['enable'] ?? 0 == 1;

        return $isEnabledForNormalUser;
    }

    public static function getPageId()
    {
```

Problem happens if you set `tx_pagetreefilter.enable = 1` in group TSconfig and then switch to user. If  `$backendUser->getTSConfig()['tx_pagetreefilter.']['enable']` is true, the value of this will be returned which is a string.

## Versions

* TYPO3 10.4.20
* PHP 7.4
* pagetreefilter: master

---

I like this extension, will probably test some more

**Comment by christophlehmann** [comment]
Thanks for the PR :)
