### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()

### ISSUE THREAD

**Issue by format-gmbh** [christophlehmann/pagetreefilter#8]
TYPO3 10.4.21
PHP 7.3.25
EXT:pagetreefilter 0.1.0
Installation is not based on composer

error message:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative() | Error thrown in file /....../...../typo3conf/ext/pagetreefilter/Classes/Controller/NewContentElementController.php in line 120. Requested URL: https://www.........de/typo3/index.php?route=%%2Fajax%%2Fpagetreefilter%%2Ffetchfilter&token=--AnonymizedToken--

**Comment by christophlehmann** [comment]
Thanks! Version 0.1.1 is released.
