### ISSUE TITLE
PHP 8 error with undefined array index

### ISSUE THREAD

**Issue by akiessling** [christophlehmann/pagetreefilter#9]
I get an error running the extension in TYPO3 11 with PHP 8:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "hideTable" in /var/www/html/src/private/typo3conf/ext/pagetreefilter/Classes/Controller/NewContentElementController.php line 63

The adminOnly setting might also need an isset check before accessing it.

I'm not sure which branch to target the issue to, NewContentElementController does not exist in master anymore. 

https://github.com/christophlehmann/pagetreefilter/blob/e7cef608214bfc1e1df2b474306fbd46eb6dcd48/Classes/Controller/WizardController.php#L69

**Comment by christophlehmann** [comment]
Thanks for reporting this. I fixed it in latest dev-master. Would you check it?
